# Baseline training config
model: yolov12s.pt                  # small pretrained YOLOv12 model
data: D:/University/Junior/Deep_Learning/PCB_Defects/dataset/Baseline/data.yaml
epochs: 100
imgsz: 512
batch: 16
optimizer: AdamW
project: runs
name: baseline
device: 0
workers: 8
save: True
plots: True
